language: generic

os:
  - linux
  - osx

dist: trusty
group: edge
  
env: TRAVIS_PYTHON_VERSION=3.6  FC=gfortran

notifications:
  email: false

git:
  depth: 3

addons:
  apt:
    packages:
      - gfortran

before_install:
    - if [[ $TRAVIS_OS_NAME == osx ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        brew update;
        brew install gcc;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi

    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r

    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda create -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - pip -q install coveralls

install:
  - python setup.py develop

script: coverage run tests/test.py -v

after_success: coveralls

